### ISSUE TITLE
TypeError: /usr/local/lib/node_modules/homebridge-config-server/lib/jade/index.jade:24

### ISSUE THREAD

**Issue by TsubokuLab** [nyata/homebridge-config-server#1]
私の環境（Raspberry Pi 3 Model B）では、ブラウザからアクセスした時に以下のエラーを吐いて落ちてしまいました。
ちょっと私が見た限りではわからなかったので、もし心当たりがありましたらご教示頂けますと幸いです。

    Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
        ┌────────────┐     
        │ 123-45-678 │     
        └────────────┘     
                       
    Access: http://192.168.0.10:1337
    Access: http://192.168.0.110:1337
    [2017-1-26 08:48:12] Homebridge is running on port 51826.
    /usr/local/lib/node_modules/homebridge-config-server/node_modules/jade/lib/runtime.js:240
      throw err;
      ^
    
    TypeError: /usr/local/lib/node_modules/homebridge-config-server/lib/jade/index.jade:24
        22|           p #{key}: #{val}
        23|       hr
      > 24|     each platform in config.platforms
        25|       each val, key in platform
        26|         p #{key}: #{val}
        27|       hr
    
    Cannot read property 'length' of undefined
        at eval (eval at exports.compile (/usr/local/lib/node_modules/homebridge-config-server/node_modules/jade/lib/index.js:218:8), <anonymous>:496:31)
        at eval (eval at exports.compile (/usr/local/lib/node_modules/homebridge-config-server/node_modules/jade/lib/index.js:218:8), <anonymous>:609:4)
        at eval (eval at exports.compile (/usr/local/lib/node_modules/homebridge-config-server/node_modules/jade/lib/index.js:218:8), <anonymous>:627:22)
        at res (/usr/local/lib/node_modules/homebridge-config-server/node_modules/jade/lib/index.js:219:38)
        at Object.exports.renderFile (/usr/local/lib/node_modules/homebridge-config-server/node_modules/jade/lib/index.js:380:38)
        at /usr/local/lib/node_modules/homebridge-config-server/lib/homebridge-config.js:149:31
        at tryToString (fs.js:426:3)
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)

**Comment by nyata** [comment]
@TsubokuLab 
ご指摘ありがとうございます。
こちらなのですが、エラー処理が足らないせいで出ているエラーで
config.platformsがない場合に落ちてしまいます。
修正を後で行いますが、現状[`config.json`](https://github.com/nfarina/homebridge/blob/master/config-sample.json)の`platforms`の項目を

```
    "platforms": []
```

のように空でもいれてあげると落ちなくなるかと思います。
お手数おかけいたします。
よろしくお願いいたします。

**Comment by TsubokuLab** [comment]
@nyata 
早速のご返信ありがとうございます。
おっしゃる通りplatforms項目を追加したところ、問題なく動くようになりました。
ありがとうございました！
